### ISSUE TITLE
JSX support in Module loaders test 

### ISSUE THREAD

**Issue by kylehotchkiss** [imjared/react-starter#1]
`test: /\.js$/,` => `test: /\.jsx?$/,`

**Comment by imjared** [comment]
this repo encourages use of `.js` file extension rather than `.jsx`. eg: https://github.com/imjared/react-starter/blob/master/src/App.js

related:
- https://github.com/facebook/react/issues/3582#issuecomment-89411479
- https://github.com/kriasoft/react-starter-kit/issues/52#issuecomment-72844613
