### ISSUE TITLE
create a deploy task

### ISSUE THREAD

**Issue by imjared** [imjared/react-starter#2]
1. Export static JS app to `public/bundle.js`
1. Compile, concatenate, and minify CSS to  `public/style.css`
1. Update HTML to use paths to assets

@jeffgreco, any requests?

**Comment by jeffgreco** [comment]
That's all I've got for now!

**Comment by imjared** [comment]
Added in 9cf3b9b. If you can think of anything else useful, feel free to open a new issue.
